### ISSUE TITLE
Confidence score issue for the first answer in Reader

### ISSUE THREAD

**Issue by dengy2016** [primeqa/create-primeqa-app#13]
For the Reader function, with different questions and answers, the confidence score of the first answer is always 100%, for example: 

![confidencescore_issue](https://user-images.githubusercontent.com/22802227/204808926-0054c5d7-1225-49ce-8757-7d57c8412ae1.png)

**Comment by SLIBM** [comment]
Wondering if we have an EST for this issue? Thanks! @kpfadnis @avisil

**Comment by SLIBM** [comment]
Are there new images released for this fix? I don't seem to see it got updated in the compose file: https://github.com/primeqa/create-primeqa-app/blob/main/docker-compose-gpu.yaml

**Comment by kpfadnis** [comment]
Closing the issue due to lack of activity. If the issue still persist, feel free to re-open.
