### ISSUE TITLE
Error E5099 when runnning a sample question answering query

### ISSUE THREAD

**Issue by maximek3** [primeqa/create-primeqa-app#4]
Hi, 

I am getting the following error message `{"detail":{"code":"E5099","message":"Something went wrong. Please contact technical support."}}`, when I run: 

> curl -X 'POST' 'http://localhost:50059/ask' -H 'accept: application/json' \ -H 'Content-Type: application/json' \ -d '{ "question": "XXX", "retriever": { "retriever_id": "ColBERTRetriever" }, "collection": { "collection_id": "XXX", "name": "Name of corresponding collection" }, "reader": { "reader_id": "ExtractiveReader" } }'

I have configured [PATCH] /`settings` as follows:

> { "retrievers": { "PrimeQA": { "service_endpoint": "primeqa:50051" }, "alpha": 0.8 }, "readers": { "PrimeQA": { "service_endpoint": "primeqa:50051", "beta": 0.7 } } }

When I run the same query in [POST]/`ask`, I get the same error message, as well as the code `500`. 

Do you have any clue where this error could come from? Thank you!

**Comment by kpfadnis** [comment]
@maximek3 Are you still noticing this issue? Please let us know.

**Comment by maximek3** [comment]
I was running this without having configured a IBM® Watson Discovery Cloud instance first, as instructed in the updated README, that may have been the issue.
