### ISSUE TITLE
No connectivity to IBM® Watson Discovery (WD)

### ISSUE THREAD

**Issue by maximek3** [primeqa/create-primeqa-app#5]
Hi,

I was trying to configure an IBM® Watson Discovery CP4D instance based retriever, using the following settings under [PATCH]/`settings`:

` {
    "retrievers": {
        "Watson_Discovery": {
            "service_endpoint": "<IBM® Watson Discovery CP4D Instance Endpoint>",
            "service_token": "<Bearer token>",
            "service_project_id": "<IBM® Watson Discovery Project ID>"
        },
        "alpha": 0.8
    },
    "readers": {
        "PrimeQA": {
            "service_endpoint": "primeqa:50051",
            "beta": 0.7
        }
    }
}`

When I then run `Execute`, I get the status 200, with the following response header:

>  access-control-allow-origin: * 
 content-length: 1374 
 content-type: application/json 
 date: Fri,04 Nov 2022 14:24:44 GMT 
 server: uvicorn 

However, I am then not able to find any retrievers when I am running the recommended tests. `http://{PUBLIC_IP}:50059/retrievers` returns `[]`.

Thanks for your help!

**Comment by apetrov-msk** [comment]
The issue is with incorrect documentation. It refers to "Watson_Discovery", while "Watson Discovery" (please note a space instead of an underscore) is expected by the code.
