### ISSUE TITLE
After installing and configuring services PrimeQA UI is not operational

### ISSUE THREAD

**Issue by apetrov-msk** [primeqa/create-primeqa-app#7]
After following up through the installation steps as well as configuring WD-based retriever as outlined in Readme.md, getting non-functional PrimeQA UI. The snapshot is attached.
<img width="793" alt="Screen Shot 2022-11-05 at 12 52 24 PM" src="https://user-images.githubusercontent.com/86081321/200131971-d0766d8e-5668-4436-afa1-8462f46d7f9a.png">

**Comment by kpfadnis** [comment]
@apetrov-msk Please double check if the UI can talk to `primeqa-orchestrator` server via monitoring network traffic tab in browser dev tools. 

**Possible Cause**: The UI container is running on a cluster and It is accessed on local machine via SSH port forwarding. In such scenario, API calls from UI to `primeqa-orchestrator` fail. 

**Temporary Resolution**:  There are two ways to address the issue
1. For now, we recommend deploying `create-primeqa-app` containers on cluster which is accessible via public IP or VPN.  
2. Use VNC to tunnel to cluster machine running  `create-primeqa-app` containers and start a browser in such VNC session.

**Comment by kpfadnis** [comment]
@apetrov-msk Closing this issue for now. If you notice this issue again, please re-open.
